server:
  error:
    include-message: always

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DATASOURCE_URL}/${DATASOURCE_DATABASE}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: ${SMTP_HOST}
    port: 587
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      smtp:
        auth: true
      ssl:
        trust: ${SMTP_HOST}
      starttls:
        enable: true

jwt:
  secret: ${JWT_SECRET}

aws:
  access: ${AMAZON_ACCESS_KEY}
  secret: ${AMAZON_SECRET_KEY}
  bucket: ${AMAZON_BUCKET_NAME}
  url: ${AMAZON_AWS_URL}

currency:
  api:
    key: ${EXCHANGE_RATES_API_KEY}
    url: ${EXCHANGE_RATES_API_URL}